[package]
name = "blink1-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blinkrs = { git = "https://github.com/coreyja/blinkrs.git", branch = "ca/main/m2" }
# blinkrs = { path = "../blinkrs" }
